cmake_minimum_required(VERSION 3.15)

if(NOT DEFINED TEST_TEMPLATE_SOURCE_DIR)
  message(FATAL_ERROR "Missing required variable: TEST_TEMPLATE_SOURCE_DIR")
endif()

function(_read_required file_path out_var)
  if(NOT EXISTS "${file_path}")
    message(FATAL_ERROR "Required file not found: ${file_path}")
  endif()
  file(READ "${file_path}" _contents)
  set(${out_var} "${_contents}" PARENT_SCOPE)
endfunction()

function(_assert_matches file_path pattern)
  _read_required("${file_path}" _contents)
  if(NOT _contents MATCHES "${pattern}")
    message(FATAL_ERROR "Expected '${file_path}' to match '${pattern}'")
  endif()
endfunction()

function(_assert_not_matches file_path pattern)
  _read_required("${file_path}" _contents)
  if(_contents MATCHES "${pattern}")
    message(FATAL_ERROR "Expected '${file_path}' not to match '${pattern}'")
  endif()
endfunction()

set(_doc_files
    "doc/template_usage.md"
    "doc/cpp_cuda_build.md"
    "doc/wrappers.md"
    "doc/versioning.md"
    "doc/documentation_workflow.md"
    "doc/testing_and_ci.md")

foreach(_doc_file IN LISTS _doc_files)
  if(NOT EXISTS "${TEST_TEMPLATE_SOURCE_DIR}/${_doc_file}")
    message(FATAL_ERROR "Missing documentation page: ${_doc_file}")
  endif()
endforeach()

_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/template_usage.md")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/cpp_cuda_build.md")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/wrappers.md")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/versioning.md")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/documentation_workflow.md")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "doc/testing_and_ci.md")

_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/template_usage.md" "Nested consumers")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/cpp_cuda_build.md" "CUDA")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/cpp_cuda_build.md" "OptiX")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/wrappers.md" "Python Package")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/wrappers.md" "MATLAB Wrapper")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/versioning.md" "WRITE_SOURCE_VERSION_FILE")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/documentation_workflow.md" "GitHub Pages")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/testing_and_ci.md" "Issue Templates")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/doc/template_usage.md" "tailor_template_cleanup.sh")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/README.md" "tailor_template_cleanup.sh")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/tailor_template_cleanup.sh" "doc/developments")
_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/tailor_template_cleanup.sh" "VerifyTemplateProjectDocsWorkflow.cmake")

set(_pages_workflow "${TEST_TEMPLATE_SOURCE_DIR}/.github/workflows/docs_pages.yml")
_read_required("${_pages_workflow}" _pages_workflow_contents)
string(REGEX MATCHALL "(^|\n)[ ]*-[ ]*README\\.md" _readme_path_filters "${_pages_workflow_contents}")
list(LENGTH _readme_path_filters _readme_path_filter_count)
if(NOT _readme_path_filter_count EQUAL 2)
  message(FATAL_ERROR
      "Expected README.md in both push and pull_request docs workflow path filters; "
      "found ${_readme_path_filter_count}")
endif()
_assert_matches("${_pages_workflow}" "actions/checkout@v6")
_assert_matches("${_pages_workflow}" "actions/configure-pages@v6")
_assert_matches("${_pages_workflow}" "actions/upload-pages-artifact@v5")
_assert_matches("${_pages_workflow}" "actions/deploy-pages@v5")
_assert_matches("${_pages_workflow}" "pages: write")
_assert_matches("${_pages_workflow}" "id-token: write")
_assert_matches("${_pages_workflow}" "deploy_pages")
_assert_matches("${_pages_workflow}" "type: boolean")
_assert_matches("${_pages_workflow}" "github.event_name == 'push'")
_assert_matches("${_pages_workflow}" "github.event_name == 'workflow_dispatch' && inputs.deploy_pages")
_assert_matches("${_pages_workflow}" "doc/html")
_assert_matches("${_pages_workflow}" "Verify published Pages output")
_assert_matches("${_pages_workflow}" "steps\\.deployment\\.outputs\\.page_url")
_assert_matches("${_pages_workflow}" "curl --fail --location --retry 5")
_assert_matches("${_pages_workflow}" "grep -F \"Template usage\"")
_assert_matches("${_pages_workflow}" "grep -F \"Documentation workflow\"")
_assert_matches("${_pages_workflow}" "grep -F \"Versioning\"")
_assert_not_matches("${_pages_workflow}" "actions/configure-pages@v[12345]")
_assert_not_matches("${_pages_workflow}" "actions/upload-pages-artifact@v[1234]")
_assert_not_matches("${_pages_workflow}" "actions/deploy-pages@v[1234]")

set(_presets "${TEST_TEMPLATE_SOURCE_DIR}/CMakePresets.json")
_assert_matches("${_presets}" "\"name\"[ ]*:[ ]*\"docs\"")
_assert_matches("${_presets}" "\"targets\"[ ]*:")
_assert_matches("${_presets}" "\"doc\"")

set(_bug_form "${TEST_TEMPLATE_SOURCE_DIR}/.github/ISSUE_TEMPLATE/bug_report.yml")
set(_feature_form "${TEST_TEMPLATE_SOURCE_DIR}/.github/ISSUE_TEMPLATE/feature_request.yml")
set(_issue_config "${TEST_TEMPLATE_SOURCE_DIR}/.github/ISSUE_TEMPLATE/config.yml")
_assert_matches("${_bug_form}" "Documentation or GitHub Pages")
_assert_matches("${_bug_form}" "Testfield or nested-library validation")
_assert_matches("${_bug_form}" "Reproduction commands")
_assert_matches("${_feature_form}" "Validation plan")
_assert_matches("${_feature_form}" "Issue templates")
_assert_matches("${_issue_config}" "blank_issues_enabled: false")

_assert_matches("${TEST_TEMPLATE_SOURCE_DIR}/CMakeLists.txt" "WRITE_SOURCE_VERSION_FILE")
_assert_not_matches("${TEST_TEMPLATE_SOURCE_DIR}/CMakeLists.txt" "\nwrite_source_VERSION_file\\(\\)\nwrite_build_VERSION_file")
