include_guard(GLOBAL)
function(handle_submodules)
    if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/lib")
        file(GLOB _submodule_dirs LIST_DIRECTORIES true "${CMAKE_CURRENT_SOURCE_DIR}/lib/*")
        foreach(_submodule_dir IN LISTS _submodule_dirs)
            if (IS_DIRECTORY "${_submodule_dir}")
            get_filename_component(_submodule_name "${_submodule_dir}" NAME)
            if (NOT _submodule_name STREQUAL "header_only")
                if (EXISTS "${_submodule_dir}/CMakeLists.txt")
                add_subdirectory("${_submodule_dir}")
                endif()
            endif()
            endif()
        endforeach()
    endif()
endfunction()