# Configure Python and MATLAB wrapper discovery, generation, installation, and
# relocatable Python runtime packaging. Generated build-link metadata remains
# checkout-only; installed packages contain only declared native artifacts.
include_guard(GLOBAL)

include(ExternalProject)

# Configure a Python extension to load co-located runtime libraries without
# embedding checkout or install-prefix paths.
function(set_python_target_properties PYTHON_TARGET OUTPUT_NAME OUTPUT_DIRECTORY)
  if(APPLE)
    set(_python_runtime_rpath "@loader_path")
  elseif(UNIX)
    set(_python_runtime_rpath "$ORIGIN")
  else()
    set(_python_runtime_rpath "")
  endif()

  # The no-op generator expression suppresses automatic configuration
  # subdirectories under multi-config generators, keeping one stable package
  # directory for metadata, staged runtimes, and the extension.
  set_target_properties(${PYTHON_TARGET} PROPERTIES
      BUILD_WITH_INSTALL_RPATH TRUE
      INSTALL_RPATH "${_python_runtime_rpath}"
      INSTALL_RPATH_USE_LINK_PATH FALSE
      OUTPUT_NAME "${OUTPUT_NAME}"
      LIBRARY_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY}$<0:>"
      RUNTIME_OUTPUT_DIRECTORY "${OUTPUT_DIRECTORY}$<0:>"
      DEBUG_POSTFIX ""
      RELWITHDEBINFO_POSTFIX ""
      TIMING_POSTFIX ""
      PROFILING_POSTFIX ""
  )
endfunction()

# Derive a prefix-relative install root from the interpreter ABI selected by
# gtwrap. Requested versions may include a patch component and therefore cannot
# identify Python's major.minor site-packages directory.
function(_resolve_python_install_root OUT_VAR)
  if(DEFINED Python_VERSION_MAJOR
      AND NOT "${Python_VERSION_MAJOR}" STREQUAL ""
      AND DEFINED Python_VERSION_MINOR
      AND NOT "${Python_VERSION_MINOR}" STREQUAL "")
    set(_python_resolved_version
      "${Python_VERSION_MAJOR}.${Python_VERSION_MINOR}")
  elseif(DEFINED PYTHON_VERSION_MAJOR
         AND NOT "${PYTHON_VERSION_MAJOR}" STREQUAL ""
         AND DEFINED PYTHON_VERSION_MINOR
         AND NOT "${PYTHON_VERSION_MINOR}" STREQUAL "")
    set(_python_resolved_version
      "${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}")
  else()
    message(FATAL_ERROR
      "Cannot derive the Python install directory because the resolved "
      "interpreter major and minor versions are unavailable.")
  endif()

  set(
    "${OUT_VAR}"
    "${CMAKE_INSTALL_LIBDIR}/python${_python_resolved_version}/site-packages"
    PARENT_SCOPE)
endfunction()

# Stage and install exact project-owned runtime targets beside a Python
# extension. The returned string contains formatted Python list entries for
# checkout-only wrapper metadata generated by the caller.
function(configure_python_runtime_artifacts
         PYTHON_TARGET
         STAGING_DIRECTORY
         INSTALL_DESTINATION
         OUT_METADATA_ENTRIES)
  if(NOT TARGET "${PYTHON_TARGET}")
    message(FATAL_ERROR
      "Python wrapper target '${PYTHON_TARGET}' does not exist.")
  endif()

  if(APPLE)
    set(_python_dependency_rpath "@loader_path")
  elseif(UNIX)
    set(_python_dependency_rpath "$ORIGIN")
  else()
    set(_python_dependency_rpath "")
  endif()

  set(_python_runtime_targets ${ARGN})
  list(REMOVE_DUPLICATES _python_runtime_targets)
  set(_python_runtime_metadata_entries "")

  foreach(_python_runtime_target IN LISTS _python_runtime_targets)
    if(NOT TARGET "${_python_runtime_target}")
      message(FATAL_ERROR
        "Python runtime dependency target '${_python_runtime_target}' does not exist.")
    endif()

    get_target_property(
      _python_runtime_target_imported
      "${_python_runtime_target}"
      IMPORTED)
    if(_python_runtime_target_imported)
      message(FATAL_ERROR
        "Python runtime dependency target '${_python_runtime_target}' is imported. "
        "Only project-owned targets can be packaged.")
    endif()

    get_target_property(
      _python_runtime_target_type
      "${_python_runtime_target}"
      TYPE)
    if(NOT _python_runtime_target_type STREQUAL "SHARED_LIBRARY"
        AND NOT _python_runtime_target_type STREQUAL "MODULE_LIBRARY")
      message(FATAL_ERROR
        "Python runtime dependency target '${_python_runtime_target}' has "
        "unsupported type '${_python_runtime_target_type}'. "
        "Expected SHARED_LIBRARY or MODULE_LIBRARY.")
    endif()

    # Give each packaged library the same loader-relative dependency contract
    # as the extension that loads it.
    set_target_properties(
      "${_python_runtime_target}"
      PROPERTIES
        BUILD_WITH_INSTALL_RPATH TRUE
        INSTALL_RPATH "${_python_dependency_rpath}"
        INSTALL_RPATH_USE_LINK_PATH FALSE)

    # Stage the complete runtime file under its target filename. A versioned
    # library also needs a file under its SONAME because that is what dependents
    # request from the dynamic loader.
    set(_python_staged_target_file
      "${STAGING_DIRECTORY}/$<TARGET_FILE_NAME:${_python_runtime_target}>")
    set(
      _python_runtime_stage_commands
      COMMAND
        "${CMAKE_COMMAND}" -E make_directory
        "${STAGING_DIRECTORY}"
      COMMAND
        "${CMAKE_COMMAND}" -E copy_if_different
        "$<TARGET_FILE:${_python_runtime_target}>"
        "${_python_staged_target_file}")
    string(APPEND
      _python_runtime_metadata_entries
      "    r\"${_python_staged_target_file}\",\n")

    get_target_property(
      _python_runtime_soversion
      "${_python_runtime_target}"
      SOVERSION)
    get_target_property(
      _python_runtime_no_soname
      "${_python_runtime_target}"
      NO_SONAME)
    if(UNIX
        AND NOT _python_runtime_soversion STREQUAL "_python_runtime_soversion-NOTFOUND"
        AND NOT _python_runtime_no_soname)
      set(_python_staged_soname_file
        "${STAGING_DIRECTORY}/$<TARGET_SONAME_FILE_NAME:${_python_runtime_target}>")
      list(
        APPEND
        _python_runtime_stage_commands
        COMMAND
          "${CMAKE_COMMAND}" -E copy_if_different
          "$<TARGET_FILE:${_python_runtime_target}>"
          "${_python_staged_soname_file}")
      string(APPEND
        _python_runtime_metadata_entries
        "    r\"${_python_staged_soname_file}\",\n")
    endif()

    # An always-run staging target refreshes copies when an explicitly
    # packaged runtime changes without forcing the wrapper itself to relink.
    string(
      MAKE_C_IDENTIFIER
      "${PYTHON_TARGET}_${_python_runtime_target}_python_runtime_stage"
      _python_runtime_stage_target)
    if(TARGET "${_python_runtime_stage_target}")
      message(FATAL_ERROR
        "Python runtime staging target '${_python_runtime_stage_target}' "
        "already exists.")
    endif()
    add_custom_target(
      "${_python_runtime_stage_target}"
      ${_python_runtime_stage_commands}
      COMMENT
        "Staging Python runtime target ${_python_runtime_target}"
      VERBATIM)
    add_dependencies(
      "${_python_runtime_stage_target}"
      "${_python_runtime_target}")
    add_dependencies("${PYTHON_TARGET}" "${_python_runtime_stage_target}")

    # Reuse CMake's target-aware install logic so versioned runtime files and
    # platform-specific DLL artifacts retain their expected names.
    install(
      TARGETS "${_python_runtime_target}"
      LIBRARY DESTINATION "${INSTALL_DESTINATION}" NAMELINK_SKIP
      RUNTIME DESTINATION "${INSTALL_DESTINATION}")
  endforeach()

  set(
    "${OUT_METADATA_ENTRIES}"
    "${_python_runtime_metadata_entries}"
    PARENT_SCOPE)
endfunction()

# Function to check validity of interface files list
function(check_interface_files_validity VALIDITY_BOOL)
  set(_interface_files ${ARGN})
  set(_is_valid TRUE)

  if("${_interface_files}" STREQUAL "")
    set(_is_valid FALSE)
  endif()

  foreach(_path IN LISTS _interface_files)
    if(NOT _path MATCHES "\\.i$")
      set(_is_valid FALSE)
      break()
    endif()
    if(NOT EXISTS "${_path}")
      message(WARNING "Wrapper interface file does not exist: ${_path}")
      set(_is_valid FALSE)
      break()
    endif()
  endforeach()

  set(${VALIDITY_BOOL} ${_is_valid} PARENT_SCOPE)
endfunction()

# Function to resolve wrap dependency
function(resolve_local_wrap_root OUT_VAR)
  set(_preferred_root "")
  if(ARGC GREATER 1)
    set(_preferred_root "${ARGV1}")
  endif()

  if(NOT "${_preferred_root}" STREQUAL "" AND EXISTS "${_preferred_root}/cmake/PybindWrap.cmake")
    set(${OUT_VAR} "${_preferred_root}" PARENT_SCOPE)
    return()
  endif()

  set(_candidates
      "${PROJECT_SOURCE_DIR}/wrap"
      "${PROJECT_SOURCE_DIR}/lib/wrap"
      "${CMAKE_CURRENT_SOURCE_DIR}/wrap"
      "${CMAKE_CURRENT_SOURCE_DIR}/lib/wrap")

  foreach(_candidate IN LISTS _candidates)
    if(EXISTS "${_candidate}/cmake/PybindWrap.cmake")
      set(${OUT_VAR} "${_candidate}" PARENT_SCOPE)
      return()
    endif()
  endforeach()

  set(${OUT_VAR} "" PARENT_SCOPE)
endfunction()

# Check if wrap submodule is already in place
function(maybe_init_wrap_submodule OUT_VAR)
  set(${OUT_VAR} "" PARENT_SCOPE)

  set(_gitmodules_file "${PROJECT_SOURCE_DIR}/.gitmodules")
  if(NOT EXISTS "${_gitmodules_file}")
    return()
  endif()

  set(_submodule_path "")
  file(READ "${_gitmodules_file}" _gitmodules_text)
  string(REGEX MATCH "path[ \t]*=[ \t]*lib/wrap" _has_lib_wrap "${_gitmodules_text}")
  string(REGEX MATCH "path[ \t]*=[ \t]*wrap" _has_wrap "${_gitmodules_text}")
  if(_has_lib_wrap)
    set(_submodule_path "lib/wrap")
  elseif(_has_wrap)
    set(_submodule_path "wrap")
  endif()

  if("${_submodule_path}" STREQUAL "")
    if(NOT GTWRAP_ADD_SUBMODULE_IF_MISSING)
      return()
    endif()

    if(NOT DEFINED GTWRAP_SUBMODULE_PATH OR "${GTWRAP_SUBMODULE_PATH}" STREQUAL "")
      set(_submodule_path "lib/wrap")
    else()
      set(_submodule_path "${GTWRAP_SUBMODULE_PATH}")
    endif()

    if(NOT DEFINED GTWRAP_SUBMODULE_REPO OR "${GTWRAP_SUBMODULE_REPO}" STREQUAL "")
      set(_gtwrap_submodule_repo "git@github.com:PeterCalifano/wrap.git")
    else()
      set(_gtwrap_submodule_repo "${GTWRAP_SUBMODULE_REPO}")
    endif()
  else()
    set(_gtwrap_submodule_repo "")
  endif()

  set(_candidate_root "${PROJECT_SOURCE_DIR}/${_submodule_path}")
  if(EXISTS "${_candidate_root}/cmake/PybindWrap.cmake")
    set(${OUT_VAR} "${_candidate_root}" PARENT_SCOPE)
    return()
  endif()

  execute_process(
    COMMAND git rev-parse --is-inside-work-tree
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE _git_repo_result
    OUTPUT_QUIET
    ERROR_QUIET
  )
  if(NOT _git_repo_result EQUAL 0)
    return()
  endif()

  if(NOT "${_gtwrap_submodule_repo}" STREQUAL "")
    get_filename_component(_submodule_parent "${_candidate_root}" DIRECTORY)
    file(MAKE_DIRECTORY "${_submodule_parent}")

    message(STATUS "Adding wrap submodule '${_gtwrap_submodule_repo}' at '${_submodule_path}'...")
    execute_process(
      COMMAND git submodule add "${_gtwrap_submodule_repo}" "${_submodule_path}"
      WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
      RESULT_VARIABLE _add_result
      OUTPUT_QUIET
      ERROR_VARIABLE _add_error
    )
    if(NOT _add_result EQUAL 0)
      string(STRIP "${_add_error}" _add_error)
      if("${_add_error}" STREQUAL "")
        set(_add_error "unknown error")
      endif()
      message(WARNING
        "Failed to add wrap submodule '${_gtwrap_submodule_repo}' at '${_submodule_path}': ${_add_error}")
      return()
    endif()
  else()
    message(STATUS "Initializing wrap submodule at '${_submodule_path}'...")
  endif()

  execute_process(
    COMMAND git submodule sync --recursive
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE _sync_result
  )
  execute_process(
    COMMAND git submodule update --init --recursive "${_submodule_path}"
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE _update_result
  )

  if(_sync_result EQUAL 0 AND _update_result EQUAL 0 AND
     EXISTS "${_candidate_root}/cmake/PybindWrap.cmake")
    set(${OUT_VAR} "${_candidate_root}" PARENT_SCOPE)
  endif()
endfunction()

# Force repo checkout if found locally
function(sync_wrap_checkout WRAP_ROOT BRANCH)
  if(NOT EXISTS "${WRAP_ROOT}/.git")
    return()
  endif()

  execute_process(
    COMMAND git remote get-url origin
    WORKING_DIRECTORY "${WRAP_ROOT}"
    RESULT_VARIABLE _origin_result
    OUTPUT_QUIET
    ERROR_QUIET
  )
  if(NOT _origin_result EQUAL 0)
    message(WARNING "Skipping wrap sync: '${WRAP_ROOT}' has no origin remote.")
    return()
  endif()

  execute_process(
    COMMAND git fetch origin "${BRANCH}"
    WORKING_DIRECTORY "${WRAP_ROOT}"
    RESULT_VARIABLE _fetch_result
  )
  if(NOT _fetch_result EQUAL 0)
    message(WARNING "Failed to fetch wrap branch '${BRANCH}' from origin. Continuing with local checkout.")
    return()
  endif()

  execute_process(
    COMMAND git rev-parse --verify --quiet "origin/${BRANCH}"
    WORKING_DIRECTORY "${WRAP_ROOT}"
    RESULT_VARIABLE _remote_branch_result
    OUTPUT_QUIET
    ERROR_QUIET
  )
  if(NOT _remote_branch_result EQUAL 0)
    message(WARNING "Remote wrap branch 'origin/${BRANCH}' not found. Continuing with local checkout.")
    return()
  endif()

  execute_process(
    COMMAND git show-ref --verify --quiet "refs/heads/${BRANCH}"
    WORKING_DIRECTORY "${WRAP_ROOT}"
    RESULT_VARIABLE _local_branch_result
    OUTPUT_QUIET
    ERROR_QUIET
  )

  if(_local_branch_result EQUAL 0)
    execute_process(
      COMMAND git checkout "${BRANCH}"
      WORKING_DIRECTORY "${WRAP_ROOT}"
      RESULT_VARIABLE _checkout_result
    )
  else()
    execute_process(
      COMMAND git checkout -B "${BRANCH}" "origin/${BRANCH}"
      WORKING_DIRECTORY "${WRAP_ROOT}"
      RESULT_VARIABLE _checkout_result
    )
  endif()
  if(NOT _checkout_result EQUAL 0)
    message(WARNING "Failed to checkout wrap branch '${BRANCH}'. Continuing with local checkout.")
    return()
  endif()

  execute_process(
    COMMAND git pull --ff-only origin "${BRANCH}"
    WORKING_DIRECTORY "${WRAP_ROOT}"
    RESULT_VARIABLE _pull_result
  )
  if(NOT _pull_result EQUAL 0)
    message(WARNING "Failed to fast-forward wrap branch '${BRANCH}' from origin. Continuing with local checkout.")
    return()
  endif()
endfunction()

### Python and MATLAB wrapper configuration using gtwrap
# Function for common wrapper configuration
function(configure_gtwrappers_common)
  set(_gtwrap_python_option_name "${LIB_NAMESPACE}_BUILD_PYTHON_WRAPPER")
  set(_gtwrap_matlab_option_name "${LIB_NAMESPACE}_BUILD_MATLAB_WRAPPER")
  set(_gtwrap_interface_var_name "${LIB_NAMESPACE}_WRAPPER_INTERFACE_FILES")
  set(_gtwrap_top_namespace_var_name "${LIB_NAMESPACE}_GTWRAP_TOP_NAMESPACE")
  set(_gtwrap_extra_deps_var_name "${LIB_NAMESPACE}_GTWRAP_DEPENDENCY_TARGETS")
  set(_gtwrap_runtime_deps_var_name
      "${LIB_NAMESPACE}_GTWRAP_RUNTIME_DEPENDENCY_TARGETS")
  set(_gtwrap_root_var_name "${LIB_NAMESPACE}_GTWRAP_ROOT_DIR")
  set(_gtwrap_autodiscover_option_name "${LIB_NAMESPACE}_WRAPPER_AUTODISCOVER_INTERFACE_FILES")

  set(${PROJECT_NAME}_WRAPPER_DISABLE_REASON "" CACHE INTERNAL
      "Reason why wrapper generation is disabled for the project." FORCE)
  set(${PROJECT_NAME}_WRAPPER_INTERFACE_FILES_EFFECTIVE "" CACHE INTERNAL
      "Effective wrapper interface files configured for the project." FORCE)

  if(NOT DEFINED GTWRAP_BRANCH)
    set(GTWRAP_BRANCH "master" CACHE STRING "wrap branch used when syncing local checkout")
  endif()
  if(NOT DEFINED GTWRAP_SYNC_TO_MASTER)
    option(GTWRAP_SYNC_TO_MASTER "Sync local wrap checkout to latest origin/<GTWRAP_BRANCH>" ON)
  endif()
  if(NOT DEFINED GTWRAP_INIT_SUBMODULE_IF_MISSING)
    option(GTWRAP_INIT_SUBMODULE_IF_MISSING
           "Initialize the wrap git submodule only after local search and find_package(gtwrap) both fail."
           ON)
  endif()
  if(NOT DEFINED GTWRAP_ADD_SUBMODULE_IF_MISSING)
    option(GTWRAP_ADD_SUBMODULE_IF_MISSING
           "Add wrap as a git submodule when it is not yet declared in .gitmodules and wrapper resolution fails."
           ON)
  endif()
  if(NOT DEFINED GTWRAP_SUBMODULE_REPO)
    set(GTWRAP_SUBMODULE_REPO "git@github.com:PeterCalifano/wrap.git" CACHE STRING
        "Git repository used when auto-adding wrap as a submodule.")
  endif()
  if(NOT DEFINED GTWRAP_SUBMODULE_PATH)
    set(GTWRAP_SUBMODULE_PATH "lib/wrap" CACHE STRING
        "Relative path used when auto-adding wrap as a submodule.")
  endif()

  if(NOT DEFINED ${_gtwrap_root_var_name})
    set(${_gtwrap_root_var_name} "" CACHE PATH
        "Optional path to a local wrap checkout (contains cmake/PybindWrap.cmake)."
        FORCE)
  endif()

  set(SEARCH_DIR_WRAP "${CMAKE_CURRENT_SOURCE_DIR}/src")
  set(_default_interface_file "${SEARCH_DIR_WRAP}/wrap_interface.i")

  option(${_gtwrap_autodiscover_option_name}
         "Automatically discover wrapper interface files under src/."
         OFF)

  if(${_gtwrap_autodiscover_option_name})
    file(GLOB_RECURSE _auto_interface_files "${SEARCH_DIR_WRAP}/*.i")
    list(SORT _auto_interface_files)
    set(${_gtwrap_interface_var_name} "${_auto_interface_files}" CACHE STRING
        "Ordered list of gtwrap interface files (.i). First element is the top-level module."
        FORCE)
  elseif(NOT DEFINED ${_gtwrap_interface_var_name})
    if(EXISTS "${_default_interface_file}")
      set(${_gtwrap_interface_var_name} "${_default_interface_file}" CACHE STRING
          "Ordered list of gtwrap interface files (.i). First element is the top-level module."
          FORCE)
    else()
      set(${_gtwrap_interface_var_name} "" CACHE STRING
          "Ordered list of gtwrap interface files (.i). First element is the top-level module."
          FORCE)
    endif()
  endif()

  if(NOT DEFINED ${_gtwrap_top_namespace_var_name})
    set(${_gtwrap_top_namespace_var_name} "${PROJECT_NAME}" CACHE STRING
        "Top namespace used in gtwrap pybind code generation."
        FORCE)
  endif()

  if(NOT DEFINED ${_gtwrap_extra_deps_var_name})
    set(${_gtwrap_extra_deps_var_name} "" CACHE STRING
        "Additional CMake targets that must be built before generating wrappers."
        FORCE)
  endif()

  if(NOT DEFINED ${_gtwrap_runtime_deps_var_name})
    set(${_gtwrap_runtime_deps_var_name} "" CACHE STRING
        "Direct project-owned shared runtime build targets packaged beside the Python wrapper."
        FORCE)
  endif()

  set(_gtwrap_interface_files ${${_gtwrap_interface_var_name}})
  set(${PROJECT_NAME}_WRAPPER_INTERFACE_FILES_EFFECTIVE "${_gtwrap_interface_files}" CACHE INTERNAL
      "Effective wrapper interface files configured for the project." FORCE)
  check_interface_files_validity(_valid_interface_files ${_gtwrap_interface_files})

  if(NOT _valid_interface_files)
    message(WARNING
      "No valid wrapper interface files were configured in '${_gtwrap_interface_var_name}'. "
      "Disabling both Python and MATLAB wrappers.")
    set(${PROJECT_NAME}_WRAPPER_DISABLE_REASON "missing_or_invalid_interface_files" CACHE INTERNAL
        "Reason why wrapper generation is disabled for the project." FORCE)
    set(${_gtwrap_python_option_name} OFF CACHE BOOL
        "Disable Python wrapper build due to missing interface files."
        FORCE)
    set(${_gtwrap_matlab_option_name} OFF CACHE BOOL
        "Disable MATLAB wrapper build due to missing interface files."
        FORCE)
    set(GTWRAP_INTERFACE_FILES "" PARENT_SCOPE)
    return()
  endif()

  set(WRAP_PYTHON_VERSION ${PROJECT_PYTHON_VERSION}
      CACHE STRING "The Python version to use for wrapping")

  set(_configured_wrap_root "${${_gtwrap_root_var_name}}")
  if(NOT "${_configured_wrap_root}" STREQUAL "" AND
     NOT EXISTS "${_configured_wrap_root}/cmake/PybindWrap.cmake")
    message(WARNING
      "${_gtwrap_root_var_name}='${_configured_wrap_root}' is invalid. "
      "Expected a directory containing cmake/PybindWrap.cmake. Ignoring override.")
    set(_configured_wrap_root "")
  endif()

  resolve_local_wrap_root(_local_wrap_root "${_configured_wrap_root}")
  if(NOT _local_wrap_root)
    find_package(gtwrap QUIET)
    if(NOT gtwrap_FOUND AND GTWRAP_INIT_SUBMODULE_IF_MISSING)
      maybe_init_wrap_submodule(_local_wrap_root)
    endif()
  endif()
  if(_local_wrap_root)
    if(GTWRAP_SYNC_TO_MASTER)
      sync_wrap_checkout("${_local_wrap_root}" "${GTWRAP_BRANCH}")
    endif()
    message(STATUS "Using local wrap checkout: ${_local_wrap_root}")

    if(${${_gtwrap_matlab_option_name}} AND
       EXISTS "${_local_wrap_root}/templates/matlab_wrapper.tpl.in")
      get_filename_component(_local_wrap_include_name "${_local_wrap_root}" NAME)
      file(READ "${_local_wrap_root}/templates/matlab_wrapper.tpl.in"
           _local_matlab_wrapper_template)
      string(REPLACE "\${GTWRAP_INCLUDE_NAME}" "${_local_wrap_include_name}"
             _local_matlab_wrapper_template "${_local_matlab_wrapper_template}")
      file(WRITE "${_local_wrap_root}/gtwrap/matlab_wrapper/matlab_wrapper.tpl"
           "${_local_matlab_wrapper_template}")
    endif()

    list(APPEND CMAKE_MODULE_PATH "${_local_wrap_root}/cmake")
    set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}" PARENT_SCOPE)

    set(GTWRAP_PYTHON_PACKAGE_DIR "${_local_wrap_root}" CACHE PATH
        "Path to gtwrap python package root." FORCE)
    set(GTWRAP_PACKAGE_DIR "${_local_wrap_root}" CACHE INTERNAL
        "Path used by gtwrap pybind custom commands for PYTHONPATH." FORCE)
    set(GTWRAP_PYTHON_PACKAGE_DIR "${_local_wrap_root}" PARENT_SCOPE)
    set(GTWRAP_PACKAGE_DIR "${_local_wrap_root}" PARENT_SCOPE)
    set(PYBIND_WRAP_SCRIPT "${_local_wrap_root}/scripts/pybind_wrap.py" CACHE FILEPATH
        "Path to pybind11 wrapping script." FORCE)
    set(MATLAB_WRAP_SCRIPT "${_local_wrap_root}/scripts/matlab_wrap.py" CACHE FILEPATH
        "Path to MATLAB wrapping script." FORCE)
    set(PYBIND_WRAP_SCRIPT "${_local_wrap_root}/scripts/pybind_wrap.py" PARENT_SCOPE)
    set(MATLAB_WRAP_SCRIPT "${_local_wrap_root}/scripts/matlab_wrap.py" PARENT_SCOPE)

    if(NOT COMMAND gtwrap_get_python_version)
      include("${_local_wrap_root}/cmake/GtwrapUtils.cmake")
    endif()
    if(NOT COMMAND pybind_wrap)
      include("${_local_wrap_root}/cmake/PybindWrap.cmake")
    endif()
    if(NOT COMMAND wrap_and_install_library)
      include("${_local_wrap_root}/cmake/MatlabWrap.cmake")
    endif()


    if(NOT COMMAND pybind11_add_module AND EXISTS "${_local_wrap_root}/pybind11/CMakeLists.txt")
      add_subdirectory(
        "${_local_wrap_root}/pybind11"
        "python/pybind11/gtwrap_${LIB_NAMESPACE}")
    endif()

    if(EXISTS "${_local_wrap_root}/matlab.h")
      get_filename_component(_local_wrap_parent "${_local_wrap_root}" DIRECTORY)
      include_directories("${_local_wrap_parent}")
      set(GTWRAP_INCLUDE_DIR "${_local_wrap_parent}" PARENT_SCOPE)
    endif()

    set(GTWRAP_ROOT_DIR "${_local_wrap_root}" PARENT_SCOPE)
  else()
    if(gtwrap_FOUND)
      message(STATUS "Using installed gtwrap package discovered by find_package(gtwrap).")

      if(DEFINED GTWRAP_PYTHON_PACKAGE_DIR AND
         NOT "${GTWRAP_PYTHON_PACKAGE_DIR}" STREQUAL "")
        set(GTWRAP_PACKAGE_DIR "${GTWRAP_PYTHON_PACKAGE_DIR}" CACHE INTERNAL
            "Path used by gtwrap pybind custom commands for PYTHONPATH." FORCE)
        set(GTWRAP_PACKAGE_DIR "${GTWRAP_PYTHON_PACKAGE_DIR}" PARENT_SCOPE)
      endif()
      if(DEFINED PYBIND_WRAP_SCRIPT AND EXISTS "${PYBIND_WRAP_SCRIPT}")
        set(PYBIND_WRAP_SCRIPT "${PYBIND_WRAP_SCRIPT}" CACHE FILEPATH
            "Path to pybind11 wrapping script." FORCE)
        set(PYBIND_WRAP_SCRIPT "${PYBIND_WRAP_SCRIPT}" PARENT_SCOPE)
      endif()
      if(DEFINED MATLAB_WRAP_SCRIPT AND EXISTS "${MATLAB_WRAP_SCRIPT}")
        set(MATLAB_WRAP_SCRIPT "${MATLAB_WRAP_SCRIPT}" CACHE FILEPATH
            "Path to MATLAB wrapping script." FORCE)
        set(MATLAB_WRAP_SCRIPT "${MATLAB_WRAP_SCRIPT}" PARENT_SCOPE)
      endif()

      if(DEFINED GTWRAP_INCLUDE_DIR AND EXISTS "${GTWRAP_INCLUDE_DIR}")
        include_directories("${GTWRAP_INCLUDE_DIR}")
        set(GTWRAP_INCLUDE_DIR "${GTWRAP_INCLUDE_DIR}" PARENT_SCOPE)
      elseif(DEFINED GTWRAP_INCLUDE_NAME AND IS_ABSOLUTE "${GTWRAP_INCLUDE_NAME}" AND EXISTS "${GTWRAP_INCLUDE_NAME}")
        include_directories("${GTWRAP_INCLUDE_NAME}")
        set(GTWRAP_INCLUDE_DIR "${GTWRAP_INCLUDE_NAME}" PARENT_SCOPE)
      endif()

      # Installed gtwrap layouts can place matlab.h under include/gtwrap/ or include/wrap/.
      # Wrap's generated MATLAB code expects <wrap/matlab.h>, so add the parent include root.
      set(_installed_matlab_h_candidates "")
      if(DEFINED GTWRAP_INCLUDE_DIR AND NOT "${GTWRAP_INCLUDE_DIR}" STREQUAL "")
        list(APPEND _installed_matlab_h_candidates
             "${GTWRAP_INCLUDE_DIR}/matlab.h"
             "${GTWRAP_INCLUDE_DIR}/gtwrap/matlab.h"
             "${GTWRAP_INCLUDE_DIR}/wrap/matlab.h")
      endif()
      if(DEFINED GTWRAP_INCLUDE_NAME AND NOT "${GTWRAP_INCLUDE_NAME}" STREQUAL "")
        list(APPEND _installed_matlab_h_candidates
             "${GTWRAP_INCLUDE_NAME}/matlab.h"
             "${GTWRAP_INCLUDE_NAME}/gtwrap/matlab.h"
             "${GTWRAP_INCLUDE_NAME}/wrap/matlab.h")
      endif()
      if(DEFINED MATLAB_WRAP_SCRIPT AND EXISTS "${MATLAB_WRAP_SCRIPT}")
        get_filename_component(_gtwrap_bin_gtwrap_dir "${MATLAB_WRAP_SCRIPT}" DIRECTORY)
        get_filename_component(_gtwrap_bin_dir "${_gtwrap_bin_gtwrap_dir}" DIRECTORY)
        get_filename_component(_gtwrap_prefix_dir "${_gtwrap_bin_dir}" DIRECTORY)
        list(APPEND _installed_matlab_h_candidates
             "${_gtwrap_prefix_dir}/include/gtwrap/matlab.h"
             "${_gtwrap_prefix_dir}/include/wrap/matlab.h")
      endif()
      if(DEFINED GTWRAP_PYTHON_PACKAGE_DIR AND EXISTS "${GTWRAP_PYTHON_PACKAGE_DIR}")
        get_filename_component(_gtwrap_lib_dir "${GTWRAP_PYTHON_PACKAGE_DIR}" DIRECTORY)
        get_filename_component(_gtwrap_prefix_dir_from_lib "${_gtwrap_lib_dir}" DIRECTORY)
        list(APPEND _installed_matlab_h_candidates
             "${_gtwrap_prefix_dir_from_lib}/include/gtwrap/matlab.h"
             "${_gtwrap_prefix_dir_from_lib}/include/wrap/matlab.h")
      endif()

      set(_installed_matlab_h "")
      foreach(_candidate IN LISTS _installed_matlab_h_candidates)
        if(EXISTS "${_candidate}")
          set(_installed_matlab_h "${_candidate}")
          break()
        endif()
      endforeach()
      if(NOT "${_installed_matlab_h}" STREQUAL "")
        get_filename_component(_installed_matlab_h_dir "${_installed_matlab_h}" DIRECTORY)
        get_filename_component(_installed_matlab_h_parent "${_installed_matlab_h_dir}" DIRECTORY)

        if(_installed_matlab_h_dir MATCHES "/(wrap|gtwrap)$")
          set(_installed_wrap_include_root "${_installed_matlab_h_parent}")
        else()
          set(_installed_wrap_include_root "${_installed_matlab_h_dir}")
        endif()

        include_directories("${_installed_wrap_include_root}")
        set(GTWRAP_INCLUDE_DIR "${_installed_wrap_include_root}" PARENT_SCOPE)
      endif()

      set(GTWRAP_ROOT_DIR "" PARENT_SCOPE)
    else()
      message(FATAL_ERROR
        "Could not locate wrap/gtwrap. Provide a local checkout at 'wrap/' or 'lib/wrap/', "
        "or set ${_gtwrap_root_var_name}=<path>, or install gtwrap so find_package(gtwrap) succeeds. "
        "Set GTWRAP_INIT_SUBMODULE_IF_MISSING=ON to allow submodule initialization when declared in .gitmodules, "
        "or GTWRAP_ADD_SUBMODULE_IF_MISSING=ON to auto-add '${GTWRAP_SUBMODULE_PATH}' from '${GTWRAP_SUBMODULE_REPO}'.")
    endif()
  endif()

  message(STATUS "Using wrapper interface files: ${_gtwrap_interface_files}")

  set(GTWRAP_INTERFACE_FILES "${_gtwrap_interface_files}" PARENT_SCOPE)
  set(GTWRAP_TOP_NAMESPACE "${${_gtwrap_top_namespace_var_name}}" PARENT_SCOPE)
  set(GTWRAP_EXTRA_DEPENDENCY_TARGETS "${${_gtwrap_extra_deps_var_name}}" PARENT_SCOPE)
  set(GTWRAP_RUNTIME_DEPENDENCY_TARGETS
      "${${_gtwrap_runtime_deps_var_name}}"
      PARENT_SCOPE)
endfunction()

# Python wrapper configuration using gtwrap
function(configure_python_gtwrapper)
  message(STATUS "Configuring Python wrap...")

  if(NOT GTWRAP_INTERFACE_FILES)
    message(FATAL_ERROR "GTWRAP_INTERFACE_FILES is empty. Cannot build Python wrapper.")
  endif()

  if(NOT COMMAND pybind_wrap)
    include(PybindWrap)
  endif()

  # Resolve Python executable for gtwrap custom commands, with preference for user override
  set(_resolved_python_executable "")
  if(DEFINED Python_EXECUTABLE AND NOT "${Python_EXECUTABLE}" STREQUAL "")
    set(_resolved_python_executable "${Python_EXECUTABLE}")
  else()
    get_property(_cached_python_executable CACHE PYTHON_EXECUTABLE PROPERTY VALUE)
    if(NOT "${_cached_python_executable}" STREQUAL "")
      set(_resolved_python_executable "${_cached_python_executable}")
    endif()
  endif()
  if(NOT "${_resolved_python_executable}" STREQUAL "")
    set(PYTHON_EXECUTABLE "${_resolved_python_executable}")
  endif()

  # Set gtwrap directory to use 
  set(_gtwrap_package_dir "")
  if(DEFINED GTWRAP_PACKAGE_DIR AND NOT "${GTWRAP_PACKAGE_DIR}" STREQUAL "")
    set(_gtwrap_package_dir "${GTWRAP_PACKAGE_DIR}")
  elseif(DEFINED GTWRAP_PYTHON_PACKAGE_DIR AND
         NOT "${GTWRAP_PYTHON_PACKAGE_DIR}" STREQUAL "")
    set(_gtwrap_package_dir "${GTWRAP_PYTHON_PACKAGE_DIR}")
  elseif(DEFINED GTWRAP_ROOT_DIR AND NOT "${GTWRAP_ROOT_DIR}" STREQUAL "")
    set(_gtwrap_package_dir "${GTWRAP_ROOT_DIR}")
  endif()

  if(NOT "${_gtwrap_package_dir}" STREQUAL "")
    set(GTWRAP_PACKAGE_DIR "${_gtwrap_package_dir}" CACHE INTERNAL
        "Path used by gtwrap pybind custom commands for PYTHONPATH." FORCE)
    set(GTWRAP_PACKAGE_DIR "${_gtwrap_package_dir}")
  endif()

  # Ensure pybind11 is available if targets are not found in the current build
  if(NOT COMMAND pybind11_add_module AND
     NOT TARGET pybind11_headers AND
     NOT TARGET pybind11::headers AND
     NOT TARGET pybind11::module)
    find_package(pybind11 CONFIG QUIET)
  endif()

  # Define command to generate Python wrapper using gtwrap's pybind_wrap function if not found
  if(NOT COMMAND pybind11_add_module)

    function(pybind11_add_module target_name)
      add_library(${target_name} MODULE ${ARGN})
      set_target_properties(${target_name} PROPERTIES PREFIX "")

      if(TARGET pybind11::module)
        target_link_libraries(${target_name} PRIVATE pybind11::module)
      elseif(TARGET pybind11::pybind11)
        target_link_libraries(${target_name} PRIVATE pybind11::pybind11)
      elseif(DEFINED GTWRAP_ROOT_DIR AND EXISTS "${GTWRAP_ROOT_DIR}/pybind11/include")
        target_include_directories(${target_name} PRIVATE "${GTWRAP_ROOT_DIR}/pybind11/include")
      endif()

      if(TARGET Python::Module)
        target_link_libraries(${target_name} PRIVATE Python::Module)
      elseif(TARGET Python3::Module)
        target_link_libraries(${target_name} PRIVATE Python3::Module)
      endif()
    endfunction()
  endif()

  # Throw fatal error if not available
  if(NOT COMMAND pybind11_add_module)
    message(FATAL_ERROR
      "pybind11_add_module is unavailable. Ensure pybind11 is loaded from gtwrap root or installed with CMake config files.")
  endif()

  # Set up Python package and build directories, and ensure __init__.py exists for the package
  set(PROJECT_PYTHON_SOURCE_DIR "${PROJECT_SOURCE_DIR}/python")
  set(PROJECT_PYTHON_PACKAGE_DIR "${PROJECT_PYTHON_SOURCE_DIR}/${PROJECT_NAME}")
  set(PROJECT_PYTHON_BUILD_DIRECTORY "${PROJECT_BINARY_DIR}/python")
  set(PROJECT_PYTHON_BUILD_PACKAGE_DIR "${PROJECT_PYTHON_BUILD_DIRECTORY}/${PROJECT_NAME}")
  set(PROJECT_PYTHON_SOURCE_METADATA_FILE "${PROJECT_PYTHON_SOURCE_DIR}/pyproject.toml")
  set(PROJECT_PYTHON_SOURCE_SETUP_FILE "${PROJECT_PYTHON_SOURCE_DIR}/setup.py")
  set(PROJECT_PYTHON_WRAPPER_LINK_FILE "${PROJECT_PYTHON_PACKAGE_DIR}/_wrapper_build.py")
  set(PROJECT_PYTHON_TARGET_NAME "${LIB_NAMESPACE}_py")
  set(${PROJECT_NAME}_PYTHON_WRAPPER_TARGET "${PROJECT_PYTHON_TARGET_NAME}" CACHE INTERNAL
      "Resolved Python wrapper target name for the project." FORCE)

  if(NOT EXISTS "${PROJECT_PYTHON_PACKAGE_DIR}")
    message(WARNING
      "Missing python package directory '${PROJECT_PYTHON_PACKAGE_DIR}'. Creating it.")
    file(MAKE_DIRECTORY "${PROJECT_PYTHON_PACKAGE_DIR}")
  endif()

  if(NOT EXISTS "${PROJECT_PYTHON_PACKAGE_DIR}/__init__.py")
    string(CONFIGURE [=[
"""Python package entrypoint for @PROJECT_NAME@ bindings."""

from __future__ import annotations

HAS_WRAPPER = False
WRAPPER_IMPORT_ERROR: ImportError | None = None

try:
    from .@PROJECT_NAME@ import *  # noqa: F401,F403
except ImportError as exc:
    WRAPPER_IMPORT_ERROR = exc
else:
    HAS_WRAPPER = True
]=] _default_python_package_init @ONLY)
    file(WRITE
      "${PROJECT_PYTHON_PACKAGE_DIR}/__init__.py"
      "${_default_python_package_init}")
  endif()

  file(MAKE_DIRECTORY "${PROJECT_PYTHON_BUILD_DIRECTORY}")

  # Write pyproject.toml for the source Python package so `pip install python/` is the public entrypoint.
  set(_pyproject_template "${PROJECT_PYTHON_SOURCE_DIR}/pyproject.toml.in")

  if(NOT EXISTS "${_pyproject_template}")
    message(WARNING
      "Missing python/pyproject.toml.in. Generating a minimal fallback template.")
    set(_pyproject_template "${PROJECT_BINARY_DIR}/python/pyproject.toml.in.fallback")
    file(WRITE "${_pyproject_template}" [=[
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "@PROJECT_NAME@"
version = "@PROJECT_VERSION@"
description = "Python bindings for @PROJECT_NAME@"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["@PROJECT_NAME@"]
include-package-data = true

[tool.setuptools.package-data]
"@PROJECT_NAME@" = ["*.so", "*.pyd", "*.dylib", "*.pyi", "**/*.pyi"]
]=])
  endif()

  configure_file(
    "${_pyproject_template}"
    "${PROJECT_PYTHON_SOURCE_METADATA_FILE}"
    @ONLY)

  set(_python_metadata_file "${PROJECT_PYTHON_SOURCE_METADATA_FILE}")

  # Write setup.py into the source python directory so the source package remains the install entrypoint.
  set(_setup_py_template "${PROJECT_PYTHON_SOURCE_DIR}/setup.py.in")
  if(EXISTS "${_setup_py_template}")
    configure_file(
      "${_setup_py_template}"
      "${PROJECT_PYTHON_SOURCE_SETUP_FILE}"
      @ONLY)
  else()
    set(_generated_setup_py_template "${PROJECT_BINARY_DIR}/python/setup.py.in.fallback")
    file(WRITE "${_generated_setup_py_template}" [=[
from setuptools import setup

setup(zip_safe=False)
]=])
    configure_file(
      "${_generated_setup_py_template}"
      "${PROJECT_PYTHON_SOURCE_SETUP_FILE}"
      @ONLY)
  endif()

  # This is required to avoid an error in modern pybind11 cmake scripts.
  if(POLICY CMP0057)
    cmake_policy(SET CMP0057 NEW)
  endif()

  set(_top_namespace "${GTWRAP_TOP_NAMESPACE}")
  if("${_top_namespace}" STREQUAL "")
    set(_top_namespace "${PROJECT_NAME}")
  endif()

  set(_link_libs "${LIBNAME_WRAP_TARGET}")
  set(_wrapper_dependencies "${LIBNAME_WRAP_TARGET}")

  if(GTWRAP_EXTRA_DEPENDENCY_TARGETS)
    list(APPEND _wrapper_dependencies ${GTWRAP_EXTRA_DEPENDENCY_TARGETS})
  endif()

  list(REMOVE_DUPLICATES _wrapper_dependencies)

  # wrap expects these customization headers for each interface; seed stubs in build tree.
  set(_pywrap_codegen_root "${PROJECT_BINARY_DIR}/${PROJECT_NAME}")
  file(MAKE_DIRECTORY "${_pywrap_codegen_root}/specializations")
  file(MAKE_DIRECTORY "${_pywrap_codegen_root}/preamble")

  # Generate empty specialization and preamble headers for each interface to avoid build errors if not existing
  foreach(_interface_file IN LISTS GTWRAP_INTERFACE_FILES)
    get_filename_component(_interface_name "${_interface_file}" NAME_WE)
    set(_spec_header "${_pywrap_codegen_root}/specializations/${_interface_name}.h")
    set(_preamble_header "${_pywrap_codegen_root}/preamble/${_interface_name}.h")
    if(NOT EXISTS "${_spec_header}")
      file(WRITE "${_spec_header}" "// Optional pybind specialization hooks for ${_interface_name}.\n")
    endif()
    if(NOT EXISTS "${_preamble_header}")
      file(WRITE "${_preamble_header}" "// Optional pybind preamble hooks for ${_interface_name}.\n")
    endif()
  endforeach()

  # Configure template for pybind module
  set(_pybind_module_template "${PROJECT_BINARY_DIR}/${PROJECT_NAME}.tpl")
  if(EXISTS "${PROJECT_SOURCE_DIR}/python/${PROJECT_NAME}.tpl")
    # Use the template from the source tree if it exists
    configure_file(
      "${PROJECT_SOURCE_DIR}/python/${PROJECT_NAME}.tpl"
      "${_pybind_module_template}"
      COPYONLY)
  
  elseif(EXISTS "${PROJECT_SOURCE_DIR}/${PROJECT_NAME}.tpl")
    # Fallback to looking for a template in the project root if not in python/
    configure_file(
      "${PROJECT_SOURCE_DIR}/${PROJECT_NAME}.tpl"
      "${_pybind_module_template}"
      COPYONLY)

  else()
    # Else write it
    file(WRITE "${_pybind_module_template}" [=[
#include <pybind11/eigen.h>
#include <pybind11/stl_bind.h>
#include <pybind11/pybind11.h>
#include <pybind11/operators.h>
#include <pybind11/iostream.h>
#include <pybind11/functional.h>

{includes}

{boost_class_export}

using namespace std;

namespace py = pybind11;

{submodules}

{module_def} {{
    m_.doc() = "pybind11 wrapper of {module_name}";

{submodules_init}

{wrapped_namespace}

}}
]=])
  endif()
  
  set(ENABLE_BOOST_SERIALIZATION OFF)
  
  # Get the main interface file and deduce names
  list(GET GTWRAP_INTERFACE_FILES 0 _main_interface_file)
  get_filename_component(_main_interface_name "${_main_interface_file}" NAME_WE)
  set(_main_interface_cpp "${_main_interface_name}.cpp")
  set(GTWRAP_PYTHON_GENERATED_CPP_DIR "python")

  # Call pybind wrapper generation function from gtwrap
  if(DEFINED GTWRAP_ADD_DOCSTRINGS AND GTWRAP_ADD_DOCSTRINGS)
    if(DEFINED BUILD_DOC_XML AND BUILD_DOC_XML AND DEFINED ${PROJECT_NAME}_DOXYGEN_XML_DIR)
      set(GTWRAP_PYTHON_DOCS_SOURCE "${${PROJECT_NAME}_DOXYGEN_XML_DIR}" CACHE PATH
          "Doxygen XML directory used for gtwrap Python docstrings." FORCE)
      message(STATUS "Python wrapper docstrings use project Doxygen XML: ${GTWRAP_PYTHON_DOCS_SOURCE}")
    else()
      message(WARNING
          "GTWRAP_ADD_DOCSTRINGS=ON but BUILD_DOC_XML is not enabled or Doxygen XML is unavailable. "
          "Generated Python wrappers will not receive project Doxygen docstrings.")
    endif()
  endif()

  pybind_wrap(${PROJECT_PYTHON_TARGET_NAME}
            "${GTWRAP_INTERFACE_FILES}"
            "${_main_interface_cpp}"
            "${PROJECT_NAME}"
            "${_top_namespace}"
            ""
            "${_pybind_module_template}"
            "${_link_libs}"
            "${_wrapper_dependencies}"
            ${ENABLE_BOOST_SERIALIZATION}
          )

  if(DEFINED GTWRAP_ADD_DOCSTRINGS AND GTWRAP_ADD_DOCSTRINGS AND
     TARGET "pybind_wrap_${PROJECT_NAME}" AND TARGET "${LIB_NAMESPACE}_doc")
    add_dependencies("pybind_wrap_${PROJECT_NAME}" "${LIB_NAMESPACE}_doc")
  endif()

  # Set python target properties, include directories, and installation rules
  set_python_target_properties(
    ${PROJECT_PYTHON_TARGET_NAME}
    "${PROJECT_NAME}"
    "${PROJECT_PYTHON_BUILD_PACKAGE_DIR}")
  target_include_directories(${PROJECT_PYTHON_TARGET_NAME}
    PRIVATE
      "${PROJECT_BINARY_DIR}"
      "${PROJECT_PYTHON_BUILD_DIRECTORY}")

  # Keep CMake installs relocatable beneath CMAKE_INSTALL_PREFIX. Installing
  # into an active environment remains the responsibility of the pip target.
  _resolve_python_install_root(_python_install_root)
  set(_python_package_install_destination
    "${_python_install_root}/${PROJECT_NAME}")

  # A shared main library is always a Python runtime artifact. Static and
  # interface targets are already linked into the extension and need no file.
  set(_python_runtime_targets)
  get_target_property(
    _python_main_runtime_target_type
    "${LIBNAME_WRAP_TARGET}"
    TYPE)
  if(_python_main_runtime_target_type STREQUAL "SHARED_LIBRARY"
      OR _python_main_runtime_target_type STREQUAL "MODULE_LIBRARY")
    list(APPEND _python_runtime_targets "${LIBNAME_WRAP_TARGET}")
  endif()
  if(GTWRAP_RUNTIME_DEPENDENCY_TARGETS)
    list(APPEND
      _python_runtime_targets
      ${GTWRAP_RUNTIME_DEPENDENCY_TARGETS})
  endif()

  configure_python_runtime_artifacts(
    "${PROJECT_PYTHON_TARGET_NAME}"
    "${PROJECT_PYTHON_BUILD_PACKAGE_DIR}"
    "${_python_package_install_destination}"
    _python_runtime_metadata_entries
    ${_python_runtime_targets})

  set(_python_wrapper_link_content
"\"\"\"Generated by CMake. Tracks the latest requested Python wrapper build.\"\"\"

WRAPPER_MODULE_PATH = r\"$<TARGET_FILE:${PROJECT_PYTHON_TARGET_NAME}>\"
WRAPPER_RUNTIME_LIBRARY_PATHS = [
${_python_runtime_metadata_entries}]
")
  file(GENERATE
    OUTPUT "${PROJECT_PYTHON_WRAPPER_LINK_FILE}"
    CONTENT "${_python_wrapper_link_content}")

  # Add import test for python module if enabled
  if(ENABLE_TESTS AND BUILD_TESTING)
    set(_python_import_test_name "${LIB_NAMESPACE}_python_import")
    set(_python_import_test_code
        "import ${PROJECT_NAME} as module_; assert getattr(module_, 'HAS_WRAPPER', False), 'Expected HAS_WRAPPER=True';")
    add_test(
      NAME ${_python_import_test_name}
      COMMAND
        ${CMAKE_COMMAND} -E env
        "PYTHONPATH=${PROJECT_PYTHON_SOURCE_DIR}:$ENV{PYTHONPATH}"
        ${PYTHON_EXECUTABLE} -c "${_python_import_test_code}")
    set_tests_properties(
      ${_python_import_test_name}
      PROPERTIES
        WORKING_DIRECTORY "${PROJECT_PYTHON_SOURCE_DIR}")
  endif()

  install(
    TARGETS ${PROJECT_PYTHON_TARGET_NAME}
    LIBRARY DESTINATION "${_python_package_install_destination}"
    RUNTIME DESTINATION "${_python_package_install_destination}")

  install(
    DIRECTORY "${PROJECT_PYTHON_PACKAGE_DIR}/"
    DESTINATION "${_python_package_install_destination}"
    PATTERN "_wrapper_build.py" EXCLUDE
    PATTERN "__pycache__" EXCLUDE
    PATTERN "*.pyc" EXCLUDE)

  if(NOT "${_python_metadata_file}" STREQUAL "")
    install(
      FILES "${_python_metadata_file}"
      DESTINATION "${_python_install_root}")
  endif()

  # Convenience target: install the source Python package after it has been linked to the latest wrapper build.
  set(_python_pip_install_target "${LIB_NAMESPACE}_python-install")
  if(NOT TARGET ${_python_pip_install_target})
    add_custom_target(
      ${_python_pip_install_target}
      COMMAND ${PYTHON_EXECUTABLE} -c "import subprocess, sys; cmd=[sys.executable, '-m', 'pip', 'install', '--no-build-isolation', '--no-deps', '.']; subprocess.check_call(cmd)"
      DEPENDS ${PROJECT_PYTHON_TARGET_NAME}
      WORKING_DIRECTORY "${PROJECT_PYTHON_SOURCE_DIR}"
      VERBATIM)
  endif()

  if(BUILD_AS_MAIN_PROJECT AND NOT TARGET python-install)
    add_custom_target(python-install DEPENDS ${_python_pip_install_target})
  endif()

  # Set python stubs generation target using pybind11-stubgen
  set(_python_stubs_target "${LIB_NAMESPACE}_python-stubs")
  if(NOT TARGET ${_python_stubs_target})
    add_custom_target(
      ${_python_stubs_target}
      COMMAND
        ${CMAKE_COMMAND} -E env
        "PYTHONPATH=${PROJECT_PYTHON_SOURCE_DIR}:$ENV{PYTHONPATH}"
        ${PYTHON_EXECUTABLE} -m pybind11_stubgen ${PROJECT_NAME} -o .
      DEPENDS ${PROJECT_PYTHON_TARGET_NAME}
      WORKING_DIRECTORY "${PROJECT_PYTHON_SOURCE_DIR}"
      VERBATIM)
  endif()

  # Add python stubs if building as main project
  if(BUILD_AS_MAIN_PROJECT)
    if(NOT TARGET python-stubs)
      add_custom_target(python-stubs DEPENDS ${_python_stubs_target})
    endif()
  endif()

endfunction()

##################################################################################################
# MATLAB wrapper configuration using gtwrap
function(configure_matlab_gtwrapper)
  message(STATUS "Configuring MATLAB wrap...")

  if(NOT GTWRAP_INTERFACE_FILES)
    message(FATAL_ERROR "GTWRAP_INTERFACE_FILES is empty. Cannot build MATLAB wrapper.")
  endif()

  set(_resolved_python_executable "")
  if(DEFINED Python_EXECUTABLE AND NOT "${Python_EXECUTABLE}" STREQUAL "")
    set(_resolved_python_executable "${Python_EXECUTABLE}")
  else()
    get_property(_cached_python_executable CACHE PYTHON_EXECUTABLE PROPERTY VALUE)
    if(NOT "${_cached_python_executable}" STREQUAL "")
      set(_resolved_python_executable "${_cached_python_executable}")
    endif()
  endif()
  if(NOT "${_resolved_python_executable}" STREQUAL "")
    set(PYTHON_EXECUTABLE "${_resolved_python_executable}")
  endif()

  if(NOT COMMAND wrap_and_install_library)
    include(MatlabWrap)
  endif()

  message(STATUS "Including MATLAB directories...")
  find_package(Matlab REQUIRED)
  set(MATLAB_MEX_INCLUDE "${Matlab_ROOT_DIR}/extern/include")

  message(STATUS "MATLAB_MEX_INCLUDE directory: ${MATLAB_MEX_INCLUDE}")
  message(STATUS "Matlab_MEX_LIBRARY directory: ${Matlab_MEX_LIBRARY}")
  message(STATUS "Matlab_MX_LIBRARY directory: ${Matlab_MX_LIBRARY}")

  include_directories(${Matlab_INCLUDE_DIRS})
  include_directories(${MATLAB_MEX_INCLUDE})
  if(DEFINED GTWRAP_INCLUDE_DIR)
    include_directories(${GTWRAP_INCLUDE_DIR})
  endif()

  if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/matlab")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/matlab")
  endif()

  set(WRAP_MEX_BUILD_STATIC_MODULE OFF)
  set(WRAP_TOOLBOX_INSTALL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/matlab")
  set(WRAP_BUILD_TYPE_POSTFIXES OFF)

  if(NOT DEFINED LIBNAME_WRAP_TARGET)
    message(FATAL_ERROR
      "LIBNAME_WRAP_TARGET variable is not defined. Cannot proceed with MATLAB wrapper build.")
  endif()

  message(STATUS "Using interface files: ${GTWRAP_INTERFACE_FILES}")
  wrap_and_install_library("${GTWRAP_INTERFACE_FILES}" "${LIBNAME_WRAP_TARGET}" "" "" "" "" OFF)
endfunction()

##################################################################################################
# Entry point function to handle gtwrap wrappers
function(handle_gtwrappers)
  set(_gtwrap_python_option_name "${LIB_NAMESPACE}_BUILD_PYTHON_WRAPPER")
  set(_gtwrap_matlab_option_name "${LIB_NAMESPACE}_BUILD_MATLAB_WRAPPER")

  set(${PROJECT_NAME}_PYTHON_WRAPPER_TARGET "" CACHE INTERNAL
      "Resolved Python wrapper target name for the project." FORCE)
  set(${PROJECT_NAME}_WRAPPER_DISABLE_REASON "" CACHE INTERNAL
      "Reason why wrapper generation is disabled for the project." FORCE)

  if(NOT DEFINED ${_gtwrap_python_option_name})
    set(${_gtwrap_python_option_name} OFF)
  endif()
  if(NOT DEFINED ${_gtwrap_matlab_option_name})
    set(${_gtwrap_matlab_option_name} OFF)
  endif()

  if(NOT ${${_gtwrap_python_option_name}} AND NOT ${${_gtwrap_matlab_option_name}})
    return()
  endif()

  configure_gtwrappers_common()

  if(BUILD_AS_MAIN_PROJECT)
    message(STATUS "GTWRAP top namespace: ${GTWRAP_TOP_NAMESPACE}")
  endif()

  if(${${_gtwrap_python_option_name}})
    configure_python_gtwrapper()
  endif()

  if(${${_gtwrap_matlab_option_name}})
    configure_matlab_gtwrapper()
  endif()
endfunction()

##################################################################################################
### Python wrapper configuration using pybind11 directly
# TODO
function(handle_pybind11_wrapper)
endfunction()
