# CMake configuration to handle submodule inclusion and automatic build
include_guard(GLOBAL)
set(LIB_SEARCH_PATH "${CMAKE_CURRENT_LIST_DIR}/../lib" CACHE PATH "Path to search for libraries/submodules")

function(handle_submodules)
    if (EXISTS "${LIB_SEARCH_PATH}")
        file(GLOB _submodule_dirs LIST_DIRECTORIES true "${LIB_SEARCH_PATH}/*")
        foreach(_submodule_dir IN LISTS _submodule_dirs)
            if (IS_DIRECTORY "${_submodule_dir}")
            get_filename_component(_submodule_name "${_submodule_dir}" NAME)
            if (NOT _submodule_name STREQUAL "header_only")
                if (EXISTS "${_submodule_dir}/CMakeLists.txt")
                add_subdirectory("${_submodule_dir}" EXCLUDE_FROM_ALL)
                endif()
            endif()
            endif()
        endforeach()
    endif()
endfunction()